(ns yalp.categories)

(def restaurants
  {:kosher "Kosher"
   :ethiopian "Ethiopian"
   :vegan "Vegan"
   :portuguese "Portuguese"
   :hotpot "Hot Pot"
   :malaysian "Malaysian"
   :japanese "Japanese"
   :scandinavian "Scandinavian"
   :mideastern "Middle Eastern"
   :burgers "Burgers"
   :taiwanese "Taiwanese"
   :irish "Irish"
   :argentine "Argentine"
   :czech "Czech"
   :diners "Diners"
   :chickenshop "Chicken Shop"
   :burmese "Burmese"
   :afghani "Afghan"
   :bangladeshi "Bangladeshi"
   :poutineries "Poutineries"
   :gluten_free "Gluten-Free"
   :hotdogs "Fast Food"
   :breakfast_brunch "Breakfast & Brunch"
   :chinese "Chinese"
   :british "British"
   :indonesian "Indonesian"
   :basque "Basque"
   :scottish "Scottish"
   :dimsum "Dim Sum"
   :tapasmallplates "Tapas/Small Plates"
   :halal "Halal"
   :hawaiian "Hawaiian"
   :lebanese "Lebanese"
   :russian "Russian"
   :latin "Latin American"
   :iberian "Iberian"
   :african "African"
   :cafes "Cafes"
   :himalayan "Himalayan/Nepalese"
   :ukrainian "Ukrainian"
   :colombian "Colombian"
   :southafrican "South African"
   :haitian "Haitian"
   :senegalese "Senegalese"
   :gastropubs "Gastropubs"
   :vietnamese "Vietnamese"
   :sushi "Sushi Bars"
   :raw_food "Live/Raw Food"
   :turkish "Turkish"
   :thai "Thai"
   :italian "Italian"
   :delis "Delis"
   :arabian "Arabian"
   :caribbean "Caribbean"
   :belgian "Belgian"
   :pizza "Pizza"
   :soulfood "Soul Food"
   :seafood "Seafood"
   :vegetarian "Vegetarian"
   :bbq "Barbeque"
   :brasseries "Brasseries"
   :peruvian "Peruvian"
   :modern_european "Modern European"
   :cheesesteaks "Cheesesteaks"
   :asianfusion "Asian Fusion"
   :mexican "Mexican"
   :austrian "Austrian"
   :pakistani "Pakistani"
   :persian "Persian/Iranian"
   :comfortfood "Comfort Food"
   :filipino "Filipino"
   :falafel "Falafel"
   :indpak "Indian"
   :fishnchips "Fish & Chips"
   :salvadoran "Salvadoran"
   :southern "Southern"
   :srilankan "Sri Lankan"
   :cajun "Cajun/Creole"
   :fondue "Fondue"
   :egyptian "Egyptian"
   :tapas "Tapas Bars"
   :korean "Korean"
   :brazilian "Brazilian"
   :ramen "Ramen"
   :moroccan "Moroccan"
   :german "German"
   :mongolian "Mongolian"
   :salad "Salad"
   :cuban "Cuban"
   :creperies "Creperies"
   :australian "Australian"
   :singaporean "Singaporean"
   :greek "Greek"
   :venezuelan "Venezuelan"
   :chicken_wings "Chicken Wings"
   :foodstands "Food Stands"
   :slovakian "Slovakian"
   :spanish "Spanish"
   :french "French"
   :sandwiches "Sandwiches"
   :cambodian "Cambodian"
:mediterranean "Mediterranean"
:steak "Steakhouses"
:hungarian "Hungarian"
:buffets "Buffets"
:laotian "Laotian"
:tex-mex "Tex-Mex"
:polish "Polish"
:soup "Soup"})

(def shopping
  {:discountstore "Dollar Store"
   :mags "Newspapers & Magazines"
   :watches "Watches"
   :bridal "Bridal"
   :mobilephones "Mobile Phones"
   :jewelry "Jewellery"
   :florists "Florists"
   :artsandcrafts "Arts & Crafts"
   :furniture "Furniture Stores"
   :outdoorgear "Outdoor Gear"
   :vapeshops "Vape Shops"
   :goldbuyers "Gold Buyers"
   :stationery "Cards & Stationery"
   :medicalsupplies "Medical Supplies"
   :framing "Framing"
   :leather "Leather Goods"
   :popupshops "Pop-up Shops"
   :shoes "Shoe Stores"
   :childcloth "Children's Clothing"
   :hobbyshops "Hobby Shops"
   :wigs "Wigs"
   :photographystores "Photography Stores & Services"
   :fitnessequipment "Fitness/Exercise Equipment"
   :cookingclasses "Cooking Classes"
   :videoandgames "Videos & Video Game Rental"
   :accessories "Accessories"
   :skateshops "Skate Shops"
   :uniforms "Uniforms"
   :outlet_stores "Outlet Stores"
   :fashion "Fashion"
   :homeandgarden "Home & Garden"
   :artsupplies "Art Supplies"
   :mattresses "Mattresses"
   :maternity "Maternity Wear"
   :hottubandpool "Hot Tub & Pool"
   :sportgoods "Sporting Goods"
   :lingerie "Lingerie"
   :custommerchandise "Customized Merchandise"
   :hardware "Hardware Stores"
   :luggage "Luggage"
   :gardening "Nurseries & Gardening"
   :bikes "Bikes"
   :kitchenandbath "Kitchen & Bath"
   :fabricstores "Fabric Stores"
   :swimwear "Swimwear"
   :appliances "Appliances"
   :flowers "Flowers & Gifts"
   :toys "Toy Stores"
   :videogamestores "Video Game Stores"
   :formalwear "Formal Wear"
   :shoppingcenters "Shopping Centres"
   :womenscloth "Women's Clothing"
   :musicvideo "Music & DVDs"
   :personal_shopping "Personal Shopping"
   :homedecor "Home Decor"
   :electronics "Electronics"
   :adult "Adult"
   :cosmetics "Cosmetics & Beauty Supply"
   :batterystores "Battery Stores"
   :bookstores "Bookstores"
   :brewingsupplies "Brewing Supplies"
   :opticians "Eyewear & Opticians"
   :antiques "Antiques"
   :galleries "Art Galleries"
   :officeequipment "Office Equipment"
   :golfequipment "Golf Equipment"
   :christmastrees "Christmas Trees"
   :skishops "Ski & Snowboard Shops"
   :tobaccoshops "Tobacco Shops"
   :vintage "Used, Vintage & Consignment"
   :computers "Computers"
   :giftshops "Gift Shops"
   :vinyl_records "Vinyl Records"
   :baby_gear "Baby Gear & Furniture"
   :thrift_stores "Thrift Stores"
   :costumes "Costumes"
   :hats "Hats"
   :wholesale_stores "Wholesale Stores"
   :media "Books, Mags, Music & Video"
   :drugstores "Drugstores"
   :menscloth "Men's Clothing"
   :fleamarkets "Flea Markets"
   :sportswear "Sports Wear"
   :hifi "High Fidelity Audio Equipment"
   :deptstores "Department Stores"
   :comicbooks "Comic Books"
   :pawn "Pawn Shops"
   :poolbilliards "Pool & Billiards"
   :knittingsupplies "Knitting Supplies"
   :musicalinstrumentsandteachers "Musical Instruments & Teachers"})

(def food
  {:butcher "Butcher"
   :distilleries "Distilleries"
   :wineries "Wineries"
   :candy "Candy Stores"
   :bagels "Bagels"
   :seafoodmarkets "Seafood Markets"
   :farmersmarket "Farmers' Market"
   :donairs "Donairs"
   :ethnicmarkets "Ethnic Food"
   :chocolate "Chocolatiers & Shops"
   :delicatessen "Delicatessen"
   :coffee "Coffee & Tea"
   :convenience "Convenience Stores"
   :breweries "Breweries"
   :fooddeliveryservices "Food Delivery Services"
   :cheese "Cheese Shops"
   :gourmet "Specialty Food"
   :juicebars "Juice Bars & Smoothies"
   :meats "Meat Shops"
   :streetvendors "Street Vendors"
   :foodtrucks "Food Trucks"
   :diyfood "Do-It-Yourself Food"
   :organic_stores "Organic Stores"
   :beer_and_wine "Beer, Wine & Spirits"
   :icecream "Ice Cream & Frozen Yogurt"
   :internetcafe "Internet Cafes"
   :bakeries "Bakeries"
   :grocery "Grocery"
   :tea "Tea Rooms"
   :healthmarkets "Health Food Store"
   :donuts "Doughnuts"
   :herbsandspices "Herbs & Spices"
   :desserts "Desserts"
   :markets "Fruits & Veggies"})

(def local
  {:web_design "Web Design"
   :musicproduction "Music Production Services"
   :electronicsrepair "Electronics Repair"
   :architects "Architects"
   :lifecoach "Life Coach"
   :shipping_centers "Shipping Centres"
   :telecommunications "Telecommunications"
   :musicinstrumentservices "Musical Instrument Services"
   :recyclingcenter "Recycling Center"
   :publicrelations "Public Relations"
   :copyshops "Printing Services"
   :couriers "Couriers & Delivery Services"
   :selfstorage "Self Storage"
   :carpet_cleaning "Carpet Cleaning"
   :sewingalterations "Sewing & Alterations"
   :snowremoval "Snow Removal"
   :mobilephonerepair "Mobile Phone Repair"
   :bike_repair_maintenance "Bike Repair/Maintenance"
   :matchmakers "Matchmakers"
   :metalfabricators "Metal Fabricators"
   :adoptionservices "Adoption Services"
   :reupholstery "Furniture Reupholstery"
   :funeralservices "Funeral Services & Cemeteries"
   :drycleaninglaundry "Dry Cleaning & Laundry"
   :pianostores "Piano Stores"
   :graphicdesign "Graphic Design"
   :notaries "Notaries"
   :appraisalservices "Appraisal Services"
   :tenantlaw "Tenant and Eviction Law"
   :pest_control "Pest Control"
   :foodbanks "Food Banks"
   :screenprinting "Screen Printing"
   :privateinvestigation "Private Investigation"
   :furniturerepair "Furniture Repair"
   :childcare "Child Care & Day Care"
   :propane "Propane"
   :septicservices "Septic Services"
   :nonprofit "Community Service/Non-Profit"
   :guitarstores "Guitar Stores"
   :vacationrentalagents "Vacation Rental Agents"
   :homeappliancerepair "Appliances & Repair"
   :softwaredevelopment "Software Development"
   :junkremovalandhauling "Junk Removal & Hauling"
   :itservices "IT Services & Computer Repair"
   :videofilmproductions "Video/Film Production"
   :officecleaning "Office Cleaning"
   :shoerepair "Shoe Repair"
   :translationservices "Translation Services"
   :recording_studios "Recording & Rehearsal Studios"
   :vacation_rentals "Vacation Rentals"
   :watch_repair "Watch Repair"
   :jewelryrepair "Jewelry Repair"
   :marketing "Marketing"
   :pianoservices "Piano Services"
   :advertising "Advertising"})

(def nightlife
  {:jazzandblues "Jazz & Blues"
   :sportsbars "Sports Bars"
   :pubs "Pubs"
   :bars "Bars"
   :pianobars "Piano Bars"
   :adultentertainment "Adult Entertainment"
   :cocktailbars "Cocktail Bars"
   :irish_pubs "Irish Pub"
   :hookah_bars "Hookah Bars"
   :danceclubs "Dance Clubs"
   :champagne_bars "Champagne Bars"
   :lounges "Lounges"
   :karaoke "Karaoke"
   :divebars "Dive Bars"
   :gaybars "Gay Bars"
   :wine_bars "Wine Bars"
   :musicvenues "Music Venues"
   :comedyclubs "Comedy Clubs"
   :poolhalls "Pool Halls"})

(def categories
  {:restaurants restaurants
   :shopping shopping
   :food food
   :local local
   :nightlife nightlife})
