(ns yalp.categories)

(def categories
  {:web_design "Web Design"
   :othersalons "Nail Salons"
   :refinishing "Refinishing Services"
   :kosher "Kosher"
   :plumbing "Plumbing"
   :ethiopian "Ethiopian"
   :mags "Newspapers & Magazines"
   :acupuncture "Acupuncture"
   :vegan "Vegan"
   :bedbreakfast "Bed & Breakfast"
   :tanningbeds "Tanning Beds"
   :motorcyclerepair "Motorcycle Repair"
   :butcher "Butcher"
   :waxing "Waxing"
   :bridal "Bridal"
   :jazzandblues "Jazz & Blues"
   :portuguese "Portuguese"
   :drywall "Drywall Installation & Repair"
   :hotpot "Hot Pot"
   :electronicsrepair "Electronics Repair"
   :distilleries "Distilleries"
   :hair_extensions "Hair Extensions"
   :wineries "Wineries"
   :sportsbars "Sports Bars"
   :malaysian "Malaysian"
   :jewelry "Jewellery"
   :fishing "Fishing"
   :tattoo "Tattoo"
   :japanese "Japanese"
   :healthtrainers "Trainers"
   :candy "Candy Stores"
   :home_inspectors "Home Inspectors"
   :florists "Florists"
   :carpenters "Carpenters"
   :taxis "Taxis"
   :scandinavian "Scandinavian"
   :mideastern "Middle Eastern"
   :bowling "Bowling"
   :estateplanning "Estate Planning Law"
   :garage_door_services "Garage Door Services"
   :pubs "Pubs"
   :poolservice "Pool & Hot Tub Service"
   :tanning "Tanning"
   :sharedofficespaces "Shared Office Spaces"
   :lifecoach "Life Coach"
   :furniture "Furniture Stores"
   :outdoorgear "Outdoor Gear"
   :bagels "Bagels"
   :groomer "Pet Groomers"
   :skate_parks "Skate Parks"
   :vapeshops "Vape Shops"
   :goldbuyers "Gold Buyers"
   :printmedia "Print Media"
   :treeservices "Tree Services"
   :burgers "Burgers"
   :eventservices "Event Planning & Services"
   :stationery "Cards & Stationery"
   :medicalsupplies "Medical Supplies"
   :shipping_centers "Shipping Centres"
   :taiwanese "Taiwanese"
   :framing "Framing"
   :tennis "Tennis"
   :movers "Movers"
   :leather "Leather Goods"
   :irish "Irish"
   :locksmiths "Keys & Locksmiths"
   :popupshops "Pop-up Shops"
   :argentine "Argentine"
   :czech "Czech"
   :stereo_installation "Car Stereo Installation"
   :scuba "Scuba Diving"
   :trampoline "Trampoline Parks"
   :yoga "Yoga"
   :diners "Diners"
   :shoes "Shoe Stores"
   :seafoodmarkets "Seafood Markets"
   :shutters "Shutters"
   :carwash "Car Wash"
   :solarinstallation "Solar Installation"
   :childcloth "Children's Clothing"
   :hobbyshops "Hobby Shops"
   :wigs "Wigs"
   :burmese "Burmese"
   :bikesharing "Bike Sharing"
   :publicrelations "Public Relations"
   :copyshops "Printing Services"
   :hypnosis "Hypnosis/Hypnotherapy"
   :couriers "Couriers & Delivery Services"
   :skincare "Skin Care"
   :catering "Caterers"
   :photographystores "Photography Stores & Services"
   :donairs "Donairs"
   :bars "Bars"
   :afghani "Afghan"
   :selfstorage "Self Storage"
   :carpet_cleaning "Carpet Cleaning"
   :spas "Day Spas"
   :pianobars "Piano Bars"
   :bangladeshi "Bangladeshi"
:poutineries "Poutineries"
:cookingclasses "Cooking Classes"
:chocolate "Chocolatiers & Shops"
:gluten_free "Gluten-Free"
:videoandgames "Videos & Video Game Rental"
:tcm "Traditional Chinese Medicine"
:sewingalterations "Sewing & Alterations"
:delicatessen "Delicatessen"
:fencing "Fencing Clubs"
:bustours "Bus Tours"
:photographers "Photographers"
:daycamps "Day Camps"
:coffee "Coffee & Tea"
:skateshops "Skate Shops"
:breakfast_brunch "Breakfast & Brunch"
:uniforms "Uniforms"
:outlet_stores "Outlet Stores"
:chinese "Chinese"
:massage "Massage"
:british "British"
:homeandgarden "Home & Garden"
:buses "Buses"
:roofing "Roofing"
:snowremoval "Snow Removal"
:gymnastics "Gymnastics"
:discgolf "Disc Golf"
:artsupplies "Art Supplies"
:adultentertainment "Adult Entertainment"
:mobilephonerepair "Mobile Phone Repair"
:indonesian "Indonesian"
:bike_repair_maintenance "Bike Repair/Maintenance"
:basque "Basque"
:convenience "Convenience Stores"
:scottish "Scottish"
:dimsum "Dim Sum"
:cocktailbars "Cocktail Bars"
:magicians "Magicians"
:mattresses "Mattresses"
:truck_rental "Truck Rental"
:testprep "Test Preparation"
:irish_pubs "Irish Pub"
:breweries "Breweries"
:tapasmallplates "Tapas/Small Plates"
:maternity "Maternity Wear"
:halal "Halal"
:pet_sitting "Pet Boarding/Pet Sitting"
:hawaiian "Hawaiian"
:lebanese "Lebanese"
:flightinstruction "Flight Instruction"
:hottubandpool "Hot Tub & Pool"
:fooddeliveryservices "Food Delivery Services"
:healthretreats "Health Retreats"
:sportgoods "Sporting Goods"
:campgrounds "Campgrounds"
:waterpurification "Water Purification Services"
:auto_detailing "Auto Detailing"
:carpetinstallation "Carpet Installation"
:lingerie "Lingerie"
:motorcycledealers "Motorcycle Dealers"
:russian "Russian"
:arcades "Arcades"
:cheese "Cheese Shops"
:gokarts "Go Karts"
:hookah_bars "Hookah Bars"
:architecturaltours "Architectural Tours"
:latin "Latin American"
:towing "Towing"
:gardens "Botanical Gardens"
:movietheaters "Cinema"
:tires "Tires"
:iberian "Iberian"
:climbing "Climbing"
:historicaltours "Historical Tours"
:petstore "Pet Stores"
:publicservicesgovt "Public Services & Government"
:casinos "Casinos"
:adoptionservices "Adoption Services"
:weightlosscenters "Weight Loss Centres"
:hairloss "Hair Loss Centers"
:cabaret "Cabaret"
:poolcleaners "Pool Cleaners"
:festivals "Festivals"
:furnitureassembly "Furniture Assembly"
:aquariumservices "Aquarium Services"
:taxservices "Tax Services"
:hardware "Hardware Stores"
:african "African"
:wedding_planning "Wedding Planning"
:guesthouses "Guest Houses"
:psychiatrists "Psychiatrists"
:reupholstery "Furniture Reupholstery"
:cafes "Cafes"
:clowns "Clowns"
:luggage "Luggage"
:danceclubs "Dance Clubs"
:himalayan "Himalayan/Nepalese"
:reststops "Rest Stops"
:gardening "Nurseries & Gardening"
:ukrainian "Ukrainian"
:dogwalkers "Dog Walkers"
:beaches "Beaches"
:skatingrinks "Skating Rinks"
:reiki "Reiki"
:colombian "Colombian"
:southafrican "South African"
:kitchenandbath "Kitchen & Bath"
:fabricstores "Fabric Stores"
:funeralservices "Funeral Services & Cemeteries"
:eventplanning "Party & Event Planning"
:haitian "Haitian"
:swimwear "Swimwear"
:appliances "Appliances"
:midwives "Midwives"
:blinds "Shades & Blinds"
:videographers "Videographers"
:gourmet "Specialty Food"
:petservices "Pet Services"
:flowers "Flowers & Gifts"
:carpeting "Carpeting"
:buildingsupplies "Building Supplies"
:dancestudio "Dance Studios"
:senegalese "Senegalese"
:propertymgmt "Property Management"
:drycleaninglaundry "Dry Cleaning & Laundry"
:toys "Toy Stores"
:beautysvc "Beauty & Spas"
:juicebars "Juice Bars & Smoothies"
:videogamestores "Video Game Stores"
:gastropubs "Gastropubs"
:rv_dealers "RV Dealers"
:vietnamese "Vietnamese"
:sushi "Sushi Bars"
:paydayloans "Cheque Cashing/Pay-day Loans"
:pianostores "Piano Stores"
:formalwear "Formal Wear"
:graphicdesign "Graphic Design"
:karaoke "Karaoke"
:meats "Meat Shops"
:divebars "Dive Bars"
:swimminglessons "Swimming Lessons/Schools"
:raw_food "Live/Raw Food"
:fertility "Fertility"
:streetvendors "Street Vendors"
:turkish "Turkish"
:thai "Thai"
:italian "Italian"
:diving "Diving"
:foodtrucks "Food Trucks"
:delis "Delis"
:womenscloth "Women's Clothing"
:pest_control "Pest Control"
:screenprinting "Screen Printing"
:privateinvestigation "Private Investigation"
:medcenters "Medical Clinics"
:mountainbiking "Mountain Biking"
:sports_clubs "Sports Clubs"
:arabian "Arabian"
:furniturerepair "Furniture Repair"
:bikerentals "Bike Rentals"
:piercing "Piercing"
:childcare "Child Care & Day Care"
:caribbean "Caribbean"
:parking "Parking"
:belgian "Belgian"
:interiordesign "Interior Design"
:privatetutors "Private Tutors"
:travelservices "Travel Services"
:hostels "Hostels"
:propane "Propane"
:musicvideo "Music & DVDs"
:homedecor "Home Decor"
:lasertag "Laser Tag"
:pizza "Pizza"
:freediving "Free Diving"
:soulfood "Soul Food"
:boxing "Boxing"
:parks "Parks"
:adult "Adult"
:cosmetics "Cosmetics & Beauty Supply"
:landscaping "Landscaping"
:seafood "Seafood"
:dentalhygienists "Dental Hygienists"
:windshieldinstallrepair "Windshield Installation & Repair"
:artclasses "Art Classes"
:vegetarian "Vegetarian"
:batterystores "Battery Stores"
:bbq "Barbeque"
:bookstores "Bookstores"
:brasseries "Brasseries"
:organic_stores "Organic Stores"
:hairremoval "Hair Removal"
:septicservices "Septic Services"
:pressurewashers "Pressure Washers"
:peruvian "Peruvian"
:modern_european "Modern European"
:limos "Limos"
:cheesesteaks "Cheesesteaks"
:guitarstores "Guitar Stores"
:football "Soccer"
:makeupartists "Makeup Artists"
:realestateagents "Real Estate Agents"
:barbers "Barbers"
:sextherapists "Sex Therapists"
:brewingsupplies "Brewing Supplies"
:investing "Investing"
:homeappliancerepair "Appliances & Repair"
:landmarks "Landmarks & Historical Buildings"
:hospitals "Hospitals"
:asianfusion "Asian Fusion"
:mexican "Mexican"
:austrian "Austrian"
:pilates "Pilates"
:home_organization "Home Organization"
:pakistani "Pakistani"
:carrental "Car Rental"
:persian "Persian/Iranian"
:windowwashing "Window Washing"
:antiques "Antiques"
:hospice "Hospice"
:comfortfood "Comfort Food"
:photoboothrentals "Photo Booth Rentals"
:archery "Archery"
:museums "Museums"
:junkremovalandhauling "Junk Removal & Hauling"
:itservices "IT Services & Computer Repair"
:filipino "Filipino"
:mobilehomes "Mobile Home Dealers"
:falafel "Falafel"
:hotels "Hotels"
:indpak "Indian"
:videofilmproductions "Video/Film Production"
:mini_golf "Mini Golf"
:fishnchips "Fish & Chips"
:taichi "Tai Chi"
:salvadoran "Salvadoran"
:southern "Southern"
:sledding "Sledding"
:health "Health & Medical"
:gaybars "Gay Bars"
:srilankan "Sri Lankan"
:icecream "Ice Cream & Frozen Yogurt"
:cajun "Cajun/Creole"
:skiing "Skiing"
:fondue "Fondue"
:chimneysweeps "Chimney Sweeps"
:gutterservices "Gutter Services"
:golfequipment "Golf Equipment"
:cabinetry "Cabinetry"
:christmastrees "Christmas Trees"
:egyptian "Egyptian"
:internetcafe "Internet Cafes"
:homehealthcare "Home Health Care"
:badminton "Badminton"
:pet_training "Pet Training"
:bakeries "Bakeries"
:tapas "Tapas Bars"
:employmentagencies "Employment Agencies"
:skishops "Ski & Snowboard Shops"
:grocery "Grocery"
:hair "Hair Salons"
:autorepair "Auto Repair"
:shoerepair "Shoe Repair"
:korean "Korean"
:translationservices "Translation Services"
:tea "Tea Rooms"
:skydiving "Skydiving"
:dog_parks "Dog Parks"
:masonry_concrete "Masonry/Concrete"
:eyelashservice "Eyelash Service"
:autoglass "Auto Glass Services"
:tobaccoshops "Tobacco Shops"
:wine_bars "Wine Bars"
:brazilian "Brazilian"
:contractors "Contractors"
:ramen "Ramen"
:vacation_rentals "Vacation Rentals"
:medicalspa "Medical Spas"
:healthmarkets "Health Food Store"
:vintage "Used, Vintage & Consignment"
:rvrental "RV Rental"
:fireplace "Fireplace Services"
:tutoring "Tutoring Centres"
:moroccan "Moroccan"
:hvac "Heating & Air Conditioning/HVAC"
:german "German"
:homestaging "Home Staging"
:mongolian "Mongolian"
:salad "Salad"
:donuts "Doughnuts"
:realestate "Real Estate"
:giftshops "Gift Shops"
:cuban "Cuban"
:creperies "Creperies"
:vinyl_records "Vinyl Records"
:car_dealers "Car Dealers"
:australian "Australian"
:singaporean "Singaporean"
:greek "Greek"
:baby_gear "Baby Gear & Furniture"
:sailing "Sailing"
:buddhist_temples "Buddhist Temples"
:venezuelan "Venezuelan"
:bodyshops "Body Shops"
:optometrists "Optometrists"
:chicken_wings "Chicken Wings"
:martialarts "Martial Arts"
:thrift_stores "Thrift Stores"
:hometheatreinstallation "Home Theatre Installation"
:costumes "Costumes"
:hats "Hats"
:foodstands "Food Stands"
:insulationinstallation "Insulation Installation"
:slovakian "Slovakian"
:watch_repair "Watch Repair"
:herbsandspices "Herbs & Spices"
:wholesale_stores "Wholesale Stores"
:spanish "Spanish"
:media "Books, Mags, Music & Video"
:drugstores "Drugstores"
:jewelryrepair "Jewelry Repair"
:french "French"
:menscloth "Men's Clothing"
:sandwiches "Sandwiches"
:cambodian "Cambodian"
:sportswear "Sports Wear"
:hifi "High Fidelity Audio Equipment"
:mediterranean "Mediterranean"
:deptstores "Department Stores"
:comedyclubs "Comedy Clubs"
:hindu_temples "Hindu Temples"
:comicbooks "Comic Books"
:steak "Steakhouses"
:hungarian "Hungarian"
:vet "Veterinarians"
:laotian "Laotian"
:walkingtours "Walking Tours"
:tex-mex "Tex-Mex"
:poolhalls "Pool Halls"
:pawn "Pawn Shops"
:desserts "Desserts"
:partysupplies "Party Supplies"
:polish "Polish"
:paintball "Paintball"
:pianoservices "Piano Services"
:soup "Soup"
:poolbilliards "Pool & Billiards"
:stucco "Stucco Services"
:knittingsupplies "Knitting Supplies"
:gardeners "Gardeners"
})
